#!/usr/bin/env python3
"""Generate engine/tests/golden.txt from the Python reference transliterator.

Format: one line per case, UTF-8, fields separated by a single TAB:
    <input>\t<expected_committed_output>

The C++ engine tests in engine/tests/test_engine.cpp load this file and assert
byte-for-byte equality. Regenerate whenever the mapping or the state machine
changes.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make prototype package importable when run from repo root.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from prototype.transliterate import Mapping, transliterate_string  # noqa: E402

MAPPING_PATH = ROOT / "mapping" / "phonetic-default.json"
CORPUS_PATH = ROOT / "prototype" / "tests" / "word_corpus.txt"
GOLDEN_PATH = ROOT / "engine" / "tests" / "golden.txt"


# The 10 worked examples + TC matrix-derived cases. Kept in sync with
# docs/phonetic-mapping-design.md §4 and §5.
WORKED_CASES = [
    ("ammaa",           "අම්මා"),
    ("ashanx",          "අශන්"),
    ("kaawx",           "කාව්"),
    ("siri",            "සිරි"),
    ("gedhara",         "ගෙදර"),
    ("magee",           "මගේ"),
    ("ispirithaalaya",  "ඉස්පිරිතාලය"),
    ("sakkaraa",        "සක්කරා"),
    ("nagaraya",        "නගරය"),
    ("laqkaawa",        "ලංකාව"),
    # TC-matrix non-backspace cases (TC-01..TC-12, minus the ones that need
    # stateful sub-events and can't be expressed as a single string).
    ("k",     "ක"),
    ("kx",    "ක්"),
    ("ka",    "ක"),
    ("kaa",   "කා"),
    ("tha",   "ත"),
    ("tx",    "ට්"),
    # Special-key smoke tests.
    ("q",     "ං"),
    ("Q",     "ඃ"),
    ("kXk",   "ක්\u200dක"),
    ("^ga",   "ඟ"),
    # Unmapped passthrough.
    ("123",       "123"),
    ("hello ",    "හෙල්ලො "),  # whatever the engine produces; must match
    ("ka, ",      "ක, "),
]


def _load_corpus():
    pairs = []
    for line in CORPUS_PATH.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        inp, want = s.split("\t")
        pairs.append((inp, want))
    return pairs


def main() -> int:
    m = Mapping.from_file(MAPPING_PATH)

    # Validate that the transliterator matches the declared worked cases and
    # corpus before we emit the golden file. This is a self-check; failure
    # means the source of truth and the declared expectations drifted.
    pairs: list[tuple[str, str]] = []

    for inp, want in WORKED_CASES:
        got = transliterate_string(inp, m)
        if got != want:
            print(
                f"WORKED mismatch: input={inp!r} got={got!r} want={want!r}",
                file=sys.stderr,
            )
            return 1
        pairs.append((inp, got))

    for inp, want in _load_corpus():
        got = transliterate_string(inp, m)
        if got != want:
            print(
                f"CORPUS mismatch: input={inp!r} got={got!r} want={want!r}",
                file=sys.stderr,
            )
            return 1
        pairs.append((inp, got))

    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    with GOLDEN_PATH.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# Cross-validation golden file. Generated by tools/generate_golden.py.\n")
        f.write("# Each non-comment line: <input>\\t<expected UTF-8 committed output>\n")
        for inp, out in pairs:
            f.write(f"{inp}\t{out}\n")

    print(f"wrote {GOLDEN_PATH} with {len(pairs)} cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
